### ISSUE TITLE
Support new `GALLEON_DIR` and `GALLEON_PROVISION_FEATURE_PACKS` when using S2I. 

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#16]
**Is your feature request related to a problem? Please describe.**

With https://issues.redhat.com/browse/CLOUD-3928, the user can specify a directory containing Galleon `provisioning.xml` as well as additional feature packs to provision when the application image is built.

To be consistent with the existing usage of `galleonLayers`, we will add 2 new fields to the `build.s2i` section.

# Additional Galleon Feature packs

* `featurePacks`
  * type: string
  * required: false
  * description: a list of comma-separated GAVS of feature pack to install during provisioning (in addition to the server own feature-pack) or an array of GAVs
  * examples: 

```yaml
build:
  s2i:
    featurePacks: "org.example:foo-feature-pack:1.0,org.foo:my-other-feature-pack:5.0" `
```

or

```yaml
build:
  s2i:
    featurePacks:
      - org.example:foo-feature-pack:1.0
      - org.foo:my-other-feature-pack:5.0
```

# Custom Galleon Directory

* `galleonDir`
  * type: string
  * required: false
  * description: a path (relative to the application root directory) to a directory containing Galleon provisioning files (such as `provisioning.xml`)
  * example: `"mysubdir/galleon"`

**Additional context**

Implementation wise, in the `BuildConfig` for the build-artifacts:
*  if the `featurePacks` is not empty, we use its value for the `GALLEON_PROVISION_FEATUREPACKS` environment variable.
* if the `galleonDir` is not empty, we use its value for the `GALLEON_DIR ` environment variable.
