### ISSUE TITLE
Use arrays to configure galleon layers

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#17]
**Is your feature request related to a problem? Please describe.**

Currently Galleon layers are configured as a string container a comma-separated list of layers to provision:

```yaml
build:
  s2i:
    galleonLayers: cloud-server,postgresql-datasource,ejb
```

This is not readable and could be improved by instead using an array of strings:

```yaml
build:
  s2i:
    galleonLayers:
      - cloud-server
      - postgresql-datasource
      - ejb
```

From an implementation perspective, this means that instead of passing directly the value of `build.s2i.galleonLayers` we will join the items with a `,`.

The type of `build.s2i.galleonLayers` will become `["string", "array", "null"]` which an additional `itemType: string` constraint to preserve backwards compatibility
