### ISSUE TITLE
Use `Ingress` as an alternative to `Route`

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#52]
**Is your feature request related to a problem? Please describe.**

The Helm Chart creates a `Route` resource to expose the application outside of the OpenShift cluster.
However this is an OpenShift-only resource and must be disabled when the chart is installed on another type of Kubernetes clusters.

The Helm Chart should allow to configure an `Ingress` instead of a `Route` for such case.

**Describe the solution you'd like**

Add new fields under `deploy.ingress` to configure an `Ingress` resource. This section should be mutually exclusive with the `deploy.route` fields.

We can add:

* `deploy.ingress.enabled` -> enables Ingress (`false` by default)
* `deploy.ingress.hostname` -> specifies the host (`wildfly.local` by default?)
* `deploy.ingress.path` -> specifies the path in the rules (`/` by default)

The generated resource would look like something similar to:

```
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: <app name>
spec:
  rules:
    - host: <deploy.ingress.hostname (wildfly.local by default) >
       http:
        paths:
          - path: <deploy.ingress.path (/ by default) >
            pathType: Prefix
            backend:
              service:
                name: <app name>
                port:
                  number: 8080
```
