### ISSUE TITLE
Configured volumes are not properly mounted 

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#63]
**Describe the bug**

It should be possible to mount a volume by configuring the `deploy.volumes` and `deploy.volumeMounts`
fields.
However, the `deploy.volumes` is not put in the proper place in the `Deployment` template and is effectively ignored.

**To Reproduce**

1. Create a secret

`kubectl create secret generic my-secret --from-literal=foo=bar`

2. Install the helm release with the configuration values:

```
deploy:
  volumeMounts:
    - name: my-secret
      mountPath: “/etc/config/my-secret”
      readOnly: true
  volumes:
    - name: my-secret
      secret:
        secretName: my-secret
```

**Expected behavior**

The secret should be mounted in `/etc/config/my-secret` and the command `cat /etc/config/my-secret/foo` should display `bar`

Instead, the `/etc/config/my-secret` directory does not exist.

 - Helm version (`$ helm version`) 2.0.0
