### ISSUE TITLE
I want to inject content from an image during S2I build step

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#64]
**Is your feature request related to a problem? Please describe.**

During S2I build, we might need to inject content in the source before it can be built.

The `BuildConfig` resource allows to do that by setting the [`source.images` array](https://docs.okd.io/latest/rest_api/workloads_apis/buildconfig-build-openshift-io-v1.html#spec-source-images-2)

We should be able to configure these `images` resource from the Helm Chart when S2I is used.

**Describe the solution you'd like**

I want to inject images during S2I build with the following configuration

```
build:
  images:
    - from:
         kind: ImageStreamTag
         name: 'my-image-to-inject:latest'
       paths:
         - sourcePath: /my-source
            destinationDir: ./my-destination-dir
```

The content of the `build.images` field is an array that complies with [`buildconfig.spec.source.images[]`](https://docs.okd.io/latest/rest_api/workloads_apis/buildconfig-build-openshift-io-v1.html#spec-source-images-2)
