### ISSUE TITLE
As an user, I want to add labels to the application image built by the chart

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#66]
**Is your feature request related to a problem? Please describe.**

The Chart for WildFly is able to build an application image. It should be possible to add labels to this image so an user could properly annotate with its own label.

**Describe the solution you'd like**

In the build.s2i section, it should possible to configure a list of labels to add to the application image.

```
build:
  s2i:
    labels:
      company: org.example
      status: prototype
      division: ACME, inc
```

All the entries in the `build.s2i.labels` would be added to the application image by inserting them in the `Dockerfile` as `LABEL` instructions.

The `build.s2i.labels" would be validated as a map of `string`, `string`
