### ISSUE TITLE
As an user, I want to add annotations and labels to the deployed application

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#67]
**Is your feature request related to a problem? Please describe.**

The Chart for WildFly is able to deploy an application using a kubernetes `Deployment`.
An user should be able to provide labels and annotations that would be added to this deployment.

**Describe the solution you'd like**

In the `deploy` section, it should be possible to specify `labels` and `annotations` that would be added to the `Deployment` created by the chart:

```yaml
deploy:
  labels:
    release: stable
    environment: dev
  annotations:
    a8r.io/owner: ACME, inc
    a8r.io/description: |-
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim 
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea 
commodo consequat.
```
