### ISSUE TITLE
As an user, I want to pull my application image from a private container registry

### ISSUE THREAD

**Issue by jmesnil** [wildfly/wildfly-charts#82]
When the deployment is created, the container image must be pullable from the container platform.
 
Public images can be pulled without any issue.
On OpenShift, any image in the OpenShift image registry can be pulled.

But if my application image is in a private container registry, I don't have the ability to provide an `imagePullSecret` that would be used to pull my image when the pods are started.

To support this use case, the `deploy` field can be enhanced with a `imagePullSecrets` array that will be used to populate the pod template `spec.imagePullSecrets` field.

When the Helm chart is installed, it will verify that there exist secrets with the specified names.

The use case would then be fulfilled with the Helm configuration:

```
image:
  name: quay.io/my-private-group/my-private-image
build:
  enabled: false
deploy:
  imagePullSecrets:
    - name: my-private-pull-secret
```

The specified secrets *MUST* exist before the Helm Chart is installed. If any specified does not exist, the installation will fail.
