### ISSUE TITLE
As a user I want to s2i from a private git source repository using a sourceSecret

### ISSUE THREAD

**Issue by bdlink** [wildfly/wildfly-charts#87]
**Is your feature request related to a problem? Please describe.**
I do not find how to build pulling from a private GitLab repository (GitHub would have same issue)

**Describe the solution you'd like**
I would like a helm.yaml such as
```
build:
  uri: https://gitlab.example.com/fbloggs/infosys.git
  mode: s2i
  ref: master
  sourceSecret: infosys-gitlab-secret
  s2i:
    version: latest
    builderImage: quay.io/wildfly/wildfly-s2i-jdk11
    runtimeImage: quay.io/wildfly/wildfly-runtime-jdk11
deploy:
  replicas: 1
```
to produce a build config portion
```
 source:
    type: Git
    git:
      uri: 'https://gitlab.example.com/fbloggs/infosys.git'
    contextDir: /
    sourceSecret:
      name: infosys-gitlab-secret

```

**Describe alternatives you've considered**
Tried existing pullSecret, but it results in a pullSecret field whereas a sourceSecret field is needed

**Additional context**
Editing the build config yaml by hand and adding the required field to define the secret works.
