### ISSUE TITLE
s2i.build.kind should be more fine grained

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-charts#92]
Today the kind field applies to both runtime and builder image. We need to set the kind for runtime and the kind for builder. kind would stay, and be applied to both, but builderKind and runtimeKind would override the kind (raw suggestion).

**Comment by jmesnil** [comment]
Thanks this sounds doable.

We would add:

```yaml
build:
  s2i:
    kind: # either ImageStreamTag or DockerImage (existing field that applies to both builder and runtime image
    builderKind: # either ImageStreamTag or DockerImage
    runtimeKind: # either ImageStreamTag or DockerImage
```

In the templates, we would use `build.s2i.builderKind` (resp. `build.s2i.runtimeKind`) to set the builder (resp. runtime) image if it is defined or defaults to `build.s2i.kind`.

So if you want to use a image stream for the builder image only, your config would look like:

```yaml
s2i:
  build:
    builderImage: jaxrs-builder-build-artifacts:latest
    builderKind: ImageStreamTag
```

This configuration would use the default runtime image (coming as a Docker image).
