### ISSUE TITLE
Generation of application image from runtime image could be disabled

### ISSUE THREAD

**Issue by jfdenise** [wildfly/wildfly-charts#93]
We are in a case were we want to only generate the xxx-build-artifacts part. We should be able to disable the runtime image generation.

**Comment by jmesnil** [comment]
wWe could add a `buildApplicationImage ` field that would not create the application image resources (`ImageStream` and `BuildConfig`) if it is set to `false`.

If this field is `false `, the user would have to disable the deployment by setting `deploy.enabled` to `true` (as we would not have an application image to deploy).

The configuration would look like:

```
build:
  git:
     ....
  s2i:
    buildApplicationImage: false
deploy:
  enabled: false
```
